export type SpeciesTag = "quy" | "trong" | "ngap-man" | "bao-ton" | "nui";

export type Species = {
  slug: string;
  name: string;
  latin: string;
  family: string;
  image: string;
  tags: SpeciesTag[];
  status: string;
  woodDensity: number;
  formFactor: number;
  allometric: "chave" | "komiyama";
  habitat: string;
  uses: string;
  rotation: string;
  notes: string;
  silviculture: string;
};

export type ForestType = {
  slug: string;
  name: string;
  image: string;
  region: string;
  summary: string;
  structure: string;
  species: string[];
  management: string;
};

export function speciesTreeSrc(slug: string) {
  return `/images/sp/${slug}-tree.jpg`;
}

export function speciesLeafSrc(slug: string) {
  return `/images/sp/${slug}-leaf.jpg`;
}

export const TAG_LABEL: Record<SpeciesTag, string> = {
  quy: "Gỗ quý",
  trong: "Trồng rừng",
  "ngap-man": "Ngập mặn",
  "bao-ton": "Bảo tồn",
  nui: "Núi cao",
};

export const SPECIES: Species[] = [
  {
    slug: "bach-dan-camal",
    name: "Bạch đàn camal",
    latin: "Eucalyptus camaldulensis",
    family: "Myrtaceae",
    image: "/images/sp/bach-dan-camal-tree.jpg",
    tags: ["trong"],
    status: "Trồng rừng ngắn ngày",
    woodDensity: 0.65,
    formFactor: 0.45,
    allometric: "chave",
    habitat: "Trung Bộ, Tây Nguyên, Đông Nam Bộ — đất bồi, ven sông, chịu hạn và ngập ngắn.",
    uses: "Dăm, bột giấy, cừ, củi. Gỗ đỏ, nặng hơn bạch đàn urô.",
    rotation: "6–8 năm bột giấy; 10–12 năm cừ.",
    notes: "Chịu hạn tốt hơn keo trên đất cát, nhưng rễ sâu — không trồng sát giếng và rừng phòng hộ đầu nguồn.",
    silviculture: "Cự ly 3×2 m. Bón lân. Hạn chế độc canh quá hai chu kỳ. Giữ đai ven suối tối thiểu 20 m.",
  },
  {
    slug: "bach-dan-lai",
    name: "Bạch đàn lai",
    latin: "Eucalyptus hybrid",
    family: "Myrtaceae",
    image: "/images/sp/bach-dan-lai-tree.jpg",
    tags: ["trong"],
    status: "Trồng rừng chủ lực",
    woodDensity: 0.55,
    formFactor: 0.45,
    allometric: "chave",
    habitat: "Đông Nam Bộ, Tây Nguyên, Trung Bộ — đất feralit, tầng trung bình.",
    uses: "Dăm gỗ, bột giấy, ván. Sinh trưởng nhanh hơn bố mẹ thuần.",
    rotation: "5–7 năm dăm; 8–10 năm gỗ lớn nếu tỉa.",
    notes: "Thường là uro × grandis (urograndis) hoặc camal × grandis. Chọn dòng đã khảo nghiệm tại vùng.",
    silviculture: "Mật độ 1.100–1.660 cây/ha. Dùng hom có nguồn gốc. Chống mối năm đầu trên đất cũ.",
  },
  {
    slug: "bach-dan-uro",
    name: "Bạch đàn urô",
    latin: "Eucalyptus urophylla",
    family: "Myrtaceae",
    image: "/images/sp/bach-dan-uro-tree.jpg",
    tags: ["trong"],
    status: "Trồng rừng ngắn ngày",
    woodDensity: 0.55,
    formFactor: 0.45,
    allometric: "chave",
    habitat: "Trung Bộ, Đông Bắc — đất dốc, tầng mỏng, nơi keo sinh trưởng kém.",
    uses: "Bột giấy, dăm, cừ. Lâm sản ngoài gỗ ít.",
    rotation: "5–7 năm bột giấy; 8–10 năm cừ.",
    notes: "Sinh trưởng nhanh, thoát nước mạnh. Không trồng gần nguồn nước sinh hoạt và rừng đặc dụng.",
    silviculture: "Cự ly 3×2 hoặc 3×3 m. Bón lân đầu vụ. Hạn chế độc canh quá 2 chu kỳ trên cùng lập địa.",
  },
  {
    slug: "keo-tai-tuong",
    name: "Keo tai tượng",
    latin: "Acacia mangium",
    family: "Fabaceae",
    image: "/images/sp/keo-tai-tuong-tree.jpg",
    tags: ["trong"],
    status: "Trồng rừng sản xuất",
    woodDensity: 0.5,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Đông Nam Bộ, Tây Nguyên, Trung Bộ — đất chua, tầng dày, mưa > 1.800 mm.",
    uses: "Dăm, MDF, ván dăm. Cố định đạm, phục hồi đất sau nương rẫy.",
    rotation: "6–8 năm dăm; 12–15 năm nếu hướng gỗ xẻ.",
    notes: "Lá giả (phyllode) rộng, quả xoắn. Dễ đổ trên đất nông có gió mạnh. Hay bị nấm rễ trên đất úng.",
    silviculture: "Cự ly 3×2 m. Không trồng nơi ngập. Tỉa cành sớm nếu lấy gỗ lớn.",
  },
  {
    slug: "keo-la-tram",
    name: "Keo lá tràm",
    latin: "Acacia auriculiformis",
    family: "Fabaceae",
    image: "/images/sp/keo-la-tram-tree.jpg",
    tags: ["trong"],
    status: "Trồng rừng chịu hạn",
    woodDensity: 0.6,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Duyên hải Trung Bộ, Đông Nam Bộ — đất cát, đất xám, chịu hạn hơn tai tượng.",
    uses: "Dăm, củi, cải tạo đất. Gỗ nặng và sẫm hơn keo tai tượng.",
    rotation: "7–10 năm. Thân hay cong nếu không tỉa.",
    notes: "Phyllode hẹp, hơi liềm. Thích hợp đai phòng hộ cát bay. Ít đổ hơn mangium.",
    silviculture: "Cự ly 2×2 đến 3×2 m. Tỉa tạo thân. Trồng hỗn giao với keo lai trên đất trung gian.",
  },
  {
    slug: "keo-lai",
    name: "Keo lai",
    latin: "Acacia mangium × A. auriculiformis",
    family: "Fabaceae",
    image: "/images/sp/keo-lai-tree.jpg",
    tags: ["trong"],
    status: "Trồng rừng chủ lực",
    woodDensity: 0.55,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Cả nước, nhất là Trung Bộ, Đông Nam Bộ, Tây Nguyên trên đất feralit.",
    uses: "Dăm gỗ, bột giấy, ván MDF; gỗ lớn 10–15 năm cho xẻ.",
    rotation: "Chu kỳ bột giấy 6–8 năm; chuyển hóa gỗ lớn 12–15 năm.",
    notes: "Loài trồng rừng sản xuất phổ biến nhất Việt Nam. Độc canh liên tục làm suy kiệt tầng đất mặt.",
    silviculture: "Cự ly 3×2 m (≈1.667 cây/ha) cho dăm; 3×3 hoặc 4×2 m nếu hướng gỗ lớn. Bón lót lân, chống cháy năm 1–2.",
  },
  {
    slug: "keo-luoi-liem",
    name: "Keo lưỡi liềm",
    latin: "Acacia crassicarpa",
    family: "Fabaceae",
    image: "/images/sp/keo-luoi-liem-tree.jpg",
    tags: ["trong"],
    status: "Trồng rừng đất phèn, ven biển",
    woodDensity: 0.55,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Đồng bằng sông Cửu Long, ven biển Trung Bộ — đất phèn, mặn nhẹ, than bùn nông.",
    uses: "Dăm, củi, phục hồi đất phèn. Chịu úng và mặn hơn các keo khác.",
    rotation: "6–8 năm trên đất phù sa; chậm hơn trên phèn nặng.",
    notes: "Phyllode dày, hình lưỡi liềm. Thích hợp thay thế một phần tràm trên đất phèn đã ôxy hóa.",
    silviculture: "Lên liếp thoát phèn. Mật độ 1.600–2.500 cây/ha. Không trồng nơi ngập triều thường xuyên.",
  },
  {
    slug: "mo",
    name: "Mỡ",
    latin: "Manglietia conifera",
    family: "Magnoliaceae",
    image: "/images/sp/mo-tree.jpg",
    tags: ["trong", "quy"],
    status: "Bản địa gỗ lớn",
    woodDensity: 0.45,
    formFactor: 0.48,
    allometric: "chave",
    habitat: "Đông Bắc, Việt Bắc — rừng thường xanh núi thấp 200–800 m, đất feralit ẩm.",
    uses: "Gỗ nhẹ, thớ thẳng — ván, đồ mộc, bao bì. Loài bản địa thay thế một phần keo.",
    rotation: "25–40 năm gỗ xẻ. Tỉa lần 1 khoảng năm thứ 8–10.",
    notes: "Tên khoa học hiện chấp nhận Magnolia conifera. Ưa ẩm, không chịu cháy. Tái sinh dưới tán tốt.",
    silviculture: "Trồng thuần hoặc hỗn giao với sa mộc, giổi. Mật độ 1.100–1.600 cây/ha. Che bóng nhẹ năm đầu.",
  },
  {
    slug: "bo-de",
    name: "Bồ đề",
    latin: "Styrax tonkinensis",
    family: "Styracaceae",
    image: "/images/sp/bo-de-tree.jpg",
    tags: ["trong"],
    status: "Cây nhựa — lâm sản ngoài gỗ",
    woodDensity: 0.4,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Tây Bắc, Việt Bắc — Sơn La, Điện Biên, Yên Bái, 400–1.000 m.",
    uses: "Nhựa cánh kiến trắng (benzoin) làm hương, dược. Gỗ nhẹ, phụ.",
    rotation: "Cạo nhựa khi D1.3 ≥ 15 cm, khoảng năm thứ 8–12. Chu kỳ gỗ 20–25 năm.",
    notes: "Cạo đúng kỹ thuật, để liền da. Quá tay làm chết cây. Thị trường nhựa biến động.",
    silviculture: "Mật độ 1.100–1.600 cây/ha. Ưa đất thoát nước. Tái sinh chồi sau chặt.",
  },
  {
    slug: "sa-moc",
    name: "Sa mộc",
    latin: "Cunninghamia lanceolata",
    family: "Cupressaceae",
    image: "/images/sp/sa-moc-tree.jpg",
    tags: ["trong", "nui"],
    status: "Trồng rừng núi thấp",
    woodDensity: 0.4,
    formFactor: 0.5,
    allometric: "chave",
    habitat: "Đông Bắc, Hoàng Liên — 400–1.200 m, khí hậu á nhiệt đới ẩm.",
    uses: "Gỗ nhẹ, dễ xẻ — cột, bao bì, đồ mộc. Tinh dầu lá.",
    rotation: "20–30 năm. Tỉa thưa giữ 600–800 cây/ha khi thành thục.",
    notes: "Lá hình mác, nhọn. Chịu lạnh hơn keo. Dễ cháy vào mùa khô Đông Bắc.",
    silviculture: "Mật độ 1.600–2.500 cây/ha. Băng cản lửa. Không trồng dưới 300 m — sâu bệnh nhiều.",
  },
  {
    slug: "sao-den",
    name: "Sao đen",
    latin: "Hopea odorata",
    family: "Dipterocarpaceae",
    image: "/images/sp/sao-den-tree.jpg",
    tags: ["quy"],
    status: "Gỗ tốt — tái sinh khó",
    woodDensity: 0.75,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Rừng mưa Đông Nam Bộ, Nam Trung Bộ, đất sâu ẩm.",
    uses: "Gỗ đóng tàu, cầu, nhà. Thớ mịn, chịu lực tốt.",
    rotation: "50–70 năm. Tái sinh tự nhiên thất thường.",
    notes: "Đòi hỏi ẩm độ cao, không chịu cháy. Tái sinh cần che bóng lúc nhỏ.",
    silviculture: "Làm giàu rừng bằng cây con dưới tán. Không trồng thuần loài trên đất trống. Giữ ẩm đất năm đầu.",
  },
  {
    slug: "dau-rai",
    name: "Dầu rái",
    latin: "Dipterocarpus alatus",
    family: "Dipterocarpaceae",
    image: "/images/sp/dau-rai-tree.jpg",
    tags: ["quy"],
    status: "Bản địa ưu thế",
    woodDensity: 0.7,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Tây Nguyên, Đông Nam Bộ, rừng thường xanh và nửa rụng lá.",
    uses: "Gỗ xẻ, dầu rái (oleoresin) trám thuyền, sơn.",
    rotation: "Gỗ lớn 40–60 năm. Cạo dầu trên cây D1.3 ≥ 40 cm theo quy trình.",
    notes: "Bạnh vè lớn, tầng vượt tán 35–45 m. Quả có cánh. Loài chủ của nhiều trạng thái IIIA.",
    silviculture: "Nuôi dưỡng tái sinh dưới tán. Tránh chặt trắng. Giữ cây mẹ 8–12 cây/ha khi khai thác chọn.",
  },
  {
    slug: "thong-ma-vi",
    name: "Thông mã vĩ",
    latin: "Pinus massoniana",
    family: "Pinaceae",
    image: "/images/sp/thong-ma-vi-tree.jpg",
    tags: ["nui", "trong"],
    status: "Trồng rừng Đông Bắc",
    woodDensity: 0.45,
    formFactor: 0.48,
    allometric: "chave",
    habitat: "Đông Bắc — Quảng Ninh, Lạng Sơn, Cao Bằng, 200–800 m, đất chua.",
    uses: "Gỗ xẻ, trụ mỏ, nhựa thông, bột giấy.",
    rotation: "20–30 năm gỗ; cạo nhựa khi D1.3 ≥ 18 cm.",
    notes: "Hai lá/bó. Chịu đất xấu. Dễ cháy. Tên 'mã vĩ' do tán như đuôi ngựa.",
    silviculture: "Mật độ 2.000–2.500 cây/ha. Tỉa + băng cản lửa. Không trồng nơi úng.",
  },
  {
    slug: "thong-ba-la",
    name: "Thông ba lá",
    latin: "Pinus kesiya",
    family: "Pinaceae",
    image: "/images/sp/thong-ba-la-tree.jpg",
    tags: ["nui", "trong"],
    status: "Bản địa núi cao",
    woodDensity: 0.5,
    formFactor: 0.48,
    allometric: "chave",
    habitat: "Lâm Đồng, Đà Lạt, cao nguyên 1.000–1.600 m.",
    uses: "Gỗ xẻ, trụ mỏ, nhựa thông. Rừng phòng hộ đầu nguồn.",
    rotation: "25–40 năm. Cạo nhựa khi D1.3 ≥ 20 cm.",
    notes: "Ba lá/bó. Dễ cháy mùa khô Đà Lạt — cần băng cản lửa và tỉa thưa.",
    silviculture: "Trồng 1.600–2.500 cây/ha. Tỉa lần 1 khi khép tán. Không trồng dưới 800 m.",
  },
  {
    slug: "thong-nhua",
    name: "Thông nhựa",
    latin: "Pinus merkusii",
    family: "Pinaceae",
    image: "/images/sp/thong-nhua-tree.jpg",
    tags: ["nui", "trong"],
    status: "Bản địa lấy nhựa",
    woodDensity: 0.55,
    formFactor: 0.48,
    allometric: "chave",
    habitat: "Tây Nguyên, Quảng Trị, Nghệ An — 400–1.200 m, đất bazan và cát.",
    uses: "Nhựa thông (colophan, terpentin), gỗ xẻ, phòng hộ.",
    rotation: "Cạo nhựa 15–25 năm; gỗ 30–40 năm.",
    notes: "Hai lá/bó, dài. Chịu cháy nền hơn thông ba lá. Quần thụ khộp-thông ở Tây Nguyên.",
    silviculture: "Mật độ 1.600–2.000 cây/ha. Cạo nhựa đúng khoanh, không khoanh quá 1/3 chu vi.",
  },
  {
    slug: "thong-caribe",
    name: "Thông caribê",
    latin: "Pinus caribaea",
    family: "Pinaceae",
    image: "/images/sp/thong-caribe-tree.jpg",
    tags: ["trong"],
    status: "Loài nhập — đất cát ven biển",
    woodDensity: 0.45,
    formFactor: 0.48,
    allometric: "chave",
    habitat: "Duyên hải Trung Bộ, Đông Nam Bộ — đất cát, tầng mỏng, nơi thông bản địa chậm lớn.",
    uses: "Gỗ bột giấy, ván, trụ. Sinh trưởng nhanh trên cát.",
    rotation: "15–25 năm. Tỉa sớm vì thân hay lệch tán.",
    notes: "Nhập từ Trung Mỹ. Ba lá/bó. Cẩn thận lai tạp và sâu róm thông.",
    silviculture: "Mật độ 1.600–2.200 cây/ha. Bón lân trên cát. Băng cản lửa bắt buộc.",
  },
  {
    slug: "lat-hoa",
    name: "Lát hoa",
    latin: "Chukrasia tabularis",
    family: "Meliaceae",
    image: "/images/sp/lat-hoa-tree.jpg",
    tags: ["quy", "trong"],
    status: "Gỗ quý bản địa",
    woodDensity: 0.65,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Bắc Trung Bộ, Đông Bắc, Tây Nguyên — rừng thường xanh và nửa rụng lá.",
    uses: "Gỗ lát đóng đồ, ván lạng, nội thất cao cấp.",
    rotation: "30–50 năm. Tỉa để thân tròn, ít mắt.",
    notes: "Lá kép, hoa trắng thơm. Gỗ có vân. Không chịu ngập. Tái sinh hạt tốt trên đất trống có che.",
    silviculture: "Mật độ 800–1.100 cây/ha. Hỗn giao với sao, dầu, giổi. Bảo vệ cây mẹ giống.",
  },
  {
    slug: "lim-xanh",
    name: "Lim xanh",
    latin: "Erythrophleum fordii",
    family: "Fabaceae",
    image: "/images/sp/lim-xanh-tree.jpg",
    tags: ["quy", "bao-ton"],
    status: "Nguy cấp — nhóm IA",
    woodDensity: 0.9,
    formFactor: 0.48,
    allometric: "chave",
    habitat: "Đông Bắc, Bắc Trung Bộ — rừng thường xanh trên đất feralit.",
    uses: "Gỗ lim đóng nhà, cầu, đóng tàu. Cấm khai thác từ rừng tự nhiên.",
    rotation: "Không kinh doanh. Trồng bảo tồn và làm giàu rừng, chu kỳ > 60 năm.",
    notes: "Còn gọi Lim. Gỗ nhóm I, rất bền. Quần thể tự nhiên bị khai thác cạn kiệt.",
    silviculture: "Trồng làm giàu dưới tán rừng nghèo, không chịu sáng hoàn toàn lúc nhỏ. Bảo vệ cây mẹ giống.",
  },
  {
    slug: "huynh",
    name: "Huỷnh",
    latin: "Tarrietia javanica",
    family: "Malvaceae",
    image: "/images/sp/huynh-tree.jpg",
    tags: ["quy", "bao-ton"],
    status: "Gỗ quý — nhóm II",
    woodDensity: 0.7,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Đông Nam Bộ, Nam Trung Bộ, Tây Nguyên — rừng thường xanh và nửa rụng lá.",
    uses: "Gỗ đóng tàu, cầu, nhà. Thớ mịn, chịu mối mọt.",
    rotation: "Không khai thác rừng tự nhiên. Làm giàu rừng, chu kỳ > 50 năm.",
    notes: "Tên hiện chấp nhận Heritiera javanica. Lá hình tim, quả có cánh. Quần thể bị chặt chọn nhiều.",
    silviculture: "Trồng dưới tán rừng nghèo. Che bóng năm đầu. Giữ cây mẹ. Không chịu cháy.",
  },
  {
    slug: "sen",
    name: "Sến",
    latin: "Madhuca pierrei",
    family: "Sapotaceae",
    image: "/images/sp/sen-tree.jpg",
    tags: ["quy", "bao-ton"],
    status: "Gỗ quý — nhóm I",
    woodDensity: 0.85,
    formFactor: 0.48,
    allometric: "chave",
    habitat: "Đông Nam Bộ, Tây Nguyên — rừng thường xanh đất sâu ẩm.",
    uses: "Gỗ sến đóng nhà, cầu, đồ chịu lực. Nhựa và hạt có dầu.",
    rotation: "Không kinh doanh từ rừng tự nhiên. Trồng bảo tồn > 60 năm.",
    notes: "Gỗ nặng, bền. Dễ nhầm với sến mật (Madhuca pasquieri). Tái sinh hạt thất thường.",
    silviculture: "Làm giàu dưới tán. Không trồng đất trống. Bảo vệ nghiêm cây mẹ giống.",
  },
  {
    slug: "tau-mat",
    name: "Táu mật",
    latin: "Vatica subglabra",
    family: "Dipterocarpaceae",
    image: "/images/sp/tau-mat-tree.jpg",
    tags: ["quy", "bao-ton"],
    status: "Gỗ quý — nhóm II",
    woodDensity: 0.8,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Đông Nam Bộ, Nam Trung Bộ — rừng mưa Dipterocarpaceae.",
    uses: "Gỗ táu đóng tàu, cầu, sàn. Chịu ẩm tốt.",
    rotation: "50–70 năm. Tái sinh cần che bóng.",
    notes: "Quả có cánh. Không chịu cháy. Cùng chi với táu nước (Vatica odorata).",
    silviculture: "Nuôi dưỡng tái sinh dưới tán. Tránh chặt trắng. Giữ ẩm đất năm đầu.",
  },
  {
    slug: "gu-lau",
    name: "Gụ lau",
    latin: "Sindora tonkinensis",
    family: "Fabaceae",
    image: "/images/sp/gu-lau-tree.jpg",
    tags: ["quy", "bao-ton"],
    status: "Đặc hữu — nguy cấp",
    woodDensity: 0.8,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Đông Bắc, Bắc Trung Bộ — rừng thường xanh trên đất feralit, địa phương hẹp.",
    uses: "Gỗ gụ đóng đồ cao cấp. Nhựa dầu. Cấm khai thác tự nhiên.",
    rotation: "Không kinh doanh. Trồng bảo tồn và vườn giống.",
    notes: "Đặc hữu Việt Nam. Lá kép, quả gỗ có gai. IUCN nguy cấp — ưu tiên in-situ.",
    silviculture: "Làm giàu dưới tán. Che bóng lúc nhỏ. Bảo vệ quần thể còn lại, không vận chuyển gỗ.",
  },
  {
    slug: "sao-hai-nam",
    name: "Sao hải nam",
    latin: "Hopea hainanensis",
    family: "Dipterocarpaceae",
    image: "/images/sp/sao-hai-nam-tree.jpg",
    tags: ["quy", "bao-ton"],
    status: "Cực kỳ nguy cấp",
    woodDensity: 0.75,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Quảng Ninh, Hải Phòng — rừng mưa trên đá vôi và đất feralit; Hải Nam (Trung Quốc).",
    uses: "Gỗ sao đóng tàu, nhà. Cấm khai thác. Giá trị bảo tồn cao.",
    rotation: "Không kinh doanh. Chỉ bảo tồn và nghiên cứu.",
    notes: "Quần thể Việt Nam rất nhỏ. Tái sinh kém. Không nhầm với sao đen (Hopea odorata).",
    silviculture: "Bảo vệ in-situ. Vườn ươm từ hạt cây mẹ đã định danh. Che bóng bắt buộc năm đầu.",
  },
  {
    slug: "de-trung-bo",
    name: "Dẻ trung bộ",
    latin: "Lithocarpus annamensis",
    family: "Fagaceae",
    image: "/images/sp/de-trung-bo-tree.jpg",
    tags: ["quy", "nui"],
    status: "Bản địa Trường Sơn",
    woodDensity: 0.7,
    formFactor: 0.48,
    allometric: "chave",
    habitat: "Trường Sơn, Nam Trung Bộ — rừng thường xanh núi thấp 400–1.200 m.",
    uses: "Gỗ dẻ xây dựng, củi. Quả (củ dẻ) thức ăn thú rừng.",
    rotation: "40–60 năm. Tái sinh hạt dưới tán tốt.",
    notes: "Cốc (cupule) gai đặc trưng Fagaceae. Loài hẹp, không trồng thuần loài trên đất trống.",
    silviculture: "Nuôi dưỡng tái sinh. Hỗn giao với giổi, re, dẻ khác. Giữ cây mẹ 6–10 cây/ha.",
  },
  {
    slug: "truong-sang",
    name: "Trường sâng",
    latin: "Amesiodendron chinense",
    family: "Sapindaceae",
    image: "/images/sp/truong-sang-tree.jpg",
    tags: ["quy", "bao-ton"],
    status: "Gỗ quý bản địa",
    woodDensity: 0.72,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Bắc Trung Bộ, Đông Bắc — rừng thường xanh núi thấp, đất feralit.",
    uses: "Gỗ đóng đồ, xây dựng. Tán rừng tự nhiên ưu thế cục bộ.",
    rotation: "40–60 năm. Tái sinh hạt khá.",
    notes: "Lá kép, hoa nhỏ. Tên cũ Amesiodendron chinensis. Không chịu cháy và đất úng.",
    silviculture: "Làm giàu rừng nghèo. Che nhẹ năm đầu. Hỗn giao với lim, gụ, sến. Giữ cây mẹ.",
  },
  {
    slug: "goi-nep",
    name: "Gội nếp",
    latin: "Aglaia spectabilis",
    family: "Meliaceae",
    image: "/images/sp/goi-nep-tree.jpg",
    tags: ["quy", "bao-ton"],
    status: "Gỗ quý bản địa",
    woodDensity: 0.7,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Đông Bắc, Bắc Trung Bộ, Tây Nguyên — rừng thường xanh ẩm.",
    uses: "Gỗ đóng đồ, xây dựng. Quả. Tầng tán rừng tự nhiên.",
    rotation: "40–60 năm. Tái sinh hạt dưới tán.",
    notes: "Lá kép, quả vàng. Còn gọi gội. Không chịu cháy. Che bóng lúc nhỏ.",
    silviculture: "Làm giàu rừng nghèo. Mật độ 400–800 cây/ha. Giữ cây mẹ. Không trồng đất trống.",
  },
  {
    slug: "tram-huong",
    name: "Trầm hương",
    latin: "Aquilaria crassna",
    family: "Thymelaeaceae",
    image: "/images/sp/tram-huong-tree.jpg",
    tags: ["quy", "bao-ton"],
    status: "CITES — cực kỳ nguy cấp",
    woodDensity: 0.4,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Trung Bộ, Tây Nguyên, Đông Nam Bộ — rừng thường xanh đất sâu.",
    uses: "Gỗ trầm (agarwood) hương liệu, dược. Cấm khai thác rừng tự nhiên.",
    rotation: "Không kinh doanh từ rừng tự nhiên. Vườn trồng có giấy phép > 8–10 năm.",
    notes: "Phân trầm chỉ hình thành khi cây bị tổn thương/nấm. Săn trộm đã cạn kiệt quần thể hoang dã.",
    silviculture: "Trồng vườn có kiểm soát, mật độ 800–1.100 cây/ha. Không kích thích trầm trên rừng tự nhiên.",
  },
  {
    slug: "khoi-tia",
    name: "Khôi tía",
    latin: "Ardisia sylvestris",
    family: "Primulaceae",
    image: "/images/sp/khoi-tia-tree.jpg",
    tags: ["bao-ton"],
    status: "Cây thuốc — dưới tán",
    woodDensity: 0.45,
    formFactor: 0.5,
    allometric: "chave",
    habitat: "Đông Bắc, Bắc Trung Bộ — dưới tán rừng ẩm, đất feralit.",
    uses: "Lá thuốc (khôi tía). Không lấy gỗ. Trồng dược liệu dưới tán.",
    rotation: "Thu lá luân phiên từ năm thứ 2–3. Không bóc trụi.",
    notes: "Lá mặt dưới tía, gân trắng. Còn viết Ardisia silvestris. Ưa ẩm, sợ nắng gắt.",
    silviculture: "Trồng dưới tán, khoảng 5.000–10.000 khóm/ha. Giữ ẩm. Không dùng thuốc trừ cỏ.",
  },
  {
    slug: "song-mat",
    name: "Song mật",
    latin: "Calamus platycanthus",
    family: "Arecaceae",
    image: "/images/sp/song-mat-tree.jpg",
    tags: ["bao-ton"],
    status: "Mây — lâm sản ngoài gỗ",
    woodDensity: 0.5,
    formFactor: 0.5,
    allometric: "chave",
    habitat: "Rừng thường xanh Bắc Bộ, Bắc Trung Bộ — dưới tán, bám cây chủ.",
    uses: "Song đan lát, nội thất mây. Không lấy gỗ thân.",
    rotation: "Thu song khi đủ tuổi 8–12 năm. Để lại cây mẹ.",
    notes: "Dây leo có gai. Cần cây chủ. Khai thác quá mức làm mất tái sinh.",
    silviculture: "Trồng dưới tán có cây bám. Mật độ 400–600 khóm/ha. Không phát sạch dưới tán.",
  },
  {
    slug: "vu-huong",
    name: "Vù hương",
    latin: "Cinnamomum parthenoxylon",
    family: "Lauraceae",
    image: "/images/sp/vu-huong-tree.jpg",
    tags: ["quy", "bao-ton"],
    status: "Gỗ quý — xá xị",
    woodDensity: 0.55,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Đông Bắc, Bắc Trung Bộ, Tây Nguyên — rừng thường xanh núi thấp.",
    uses: "Gỗ xá xị, tinh dầu safrole. Còn gọi re hương. Cấm khai thác tự nhiên bừa bãi.",
    rotation: "40–60 năm gỗ. Tinh dầu từ lá/gỗ theo giấy phép.",
    notes: "Gỗ thơm. Dễ nhầm các Cinnamomum khác. Quần thể bị chặt lấy dầu.",
    silviculture: "Làm giàu dưới tán. Che bóng năm đầu. Bảo vệ cây mẹ. Không cạo vỏ vòng quanh.",
  },
  {
    slug: "khuyet-nhi-hai-nam",
    name: "Khuyết nhị Hải nam",
    latin: "Endiandra hainanensis",
    family: "Lauraceae",
    image: "/images/sp/khuyet-nhi-hai-nam-tree.jpg",
    tags: ["bao-ton", "quy"],
    status: "Hẹp — bảo tồn",
    woodDensity: 0.6,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Quảng Ninh, Hải Phòng, Hải Nam — rừng mưa trên đá vôi và đất feralit.",
    uses: "Gỗ Lauraceae. Giá trị bảo tồn cao hơn kinh doanh.",
    rotation: "Không kinh doanh. Chỉ bảo tồn và nghiên cứu.",
    notes: "Quần thể rất nhỏ. Lá đơn, quả. Không nhầm Beilschmiedia. Ưa ẩm, sợ cháy.",
    silviculture: "Bảo vệ in-situ. Ươm hạt cây mẹ. Che bóng bắt buộc. Không chuyển gỗ.",
  },
  {
    slug: "man-voi",
    name: "Mán voi",
    latin: "Laportea urentissima",
    family: "Urticaceae",
    image: "/images/sp/man-voi-tree.jpg",
    tags: ["bao-ton"],
    status: "Cây dưới tán — lông đốt",
    woodDensity: 0.35,
    formFactor: 0.45,
    allometric: "chave",
    habitat: "Rừng ẩm Bắc Bộ, Bắc Trung Bộ — ven suối, đất giàu mùn.",
    uses: "Không lấy gỗ. Chỉ thị rừng ẩm. Tránh tiếp xúc — lông đốt rất mạnh.",
    rotation: "Không kinh doanh.",
    notes: "Hiện xếp Dendrocnide urentissima. Lá rộng, lông đốt gây bỏng da hàng giờ. Không đụng tay trần.",
    silviculture: "Giữ trong rừng tự nhiên. Không phát thực bì ven suối. Đi hiện trường phải nhận biết trước.",
  },
  {
    slug: "de-bac-giang",
    name: "Dẻ Bắc Giang",
    latin: "Lithocarpus bacgiangensis",
    family: "Fagaceae",
    image: "/images/sp/de-bac-giang-tree.jpg",
    tags: ["quy", "nui"],
    status: "Bản địa hẹp",
    woodDensity: 0.7,
    formFactor: 0.48,
    allometric: "chave",
    habitat: "Đông Bắc — Bắc Giang, Lạng Sơn, Quảng Ninh — rừng thường xanh núi thấp.",
    uses: "Gỗ dẻ xây dựng. Quả thức ăn thú. Loài hẹp, ưu tiên bảo tồn.",
    rotation: "40–60 năm. Tái sinh hạt dưới tán.",
    notes: "Cốc gai Fagaceae. Không trồng thuần loài. Dễ nhầm dẻ trung bộ và dẻ khác.",
    silviculture: "Nuôi dưỡng tái sinh. Giữ cây mẹ 6–10 cây/ha. Hỗn giao với giổi, re, trường sâng.",
  },
  {
    slug: "thiet-dinh",
    name: "Thiết đinh",
    latin: "Markhamia stipulata",
    family: "Bignoniaceae",
    image: "/images/sp/thiet-dinh-tree.jpg",
    tags: ["quy", "trong"],
    status: "Gỗ bản địa — trồng phân tán",
    woodDensity: 0.7,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Bắc Bộ, Bắc Trung Bộ — rừng thứ sinh, đất feralit, chịu hạn vừa.",
    uses: "Gỗ cứng đóng đồ, cột. Hoa vàng. Cây bóng và làm giàu.",
    rotation: "25–40 năm. Tỉa tạo thân thẳng.",
    notes: "Lá kép, hoa vàng ống. Còn viết M. stipullata. Ưa sáng lúc lớn.",
    silviculture: "Mật độ 800–1.100 cây/ha. Trồng thuần hoặc hỗn giao. Tỉa cành sớm.",
  },
  {
    slug: "rau-sang",
    name: "Rau sắng",
    latin: "Melientha suavis",
    family: "Opiliaceae",
    image: "/images/sp/rau-sang-tree.jpg",
    tags: ["bao-ton"],
    status: "Cây thực phẩm rừng",
    woodDensity: 0.5,
    formFactor: 0.48,
    allometric: "chave",
    habitat: "Bắc Bộ, Bắc Trung Bộ, Tây Nguyên — dưới tán rừng thường xanh.",
    uses: "Ngọn và lá ăn (rau sắng). Không lấy gỗ. Đặc sản rừng.",
    rotation: "Thu hái ngọn từ năm thứ 3–4, để lại đủ lá.",
    notes: "Còn viết Meliantha suavis. Ưa ẩm. Khai thác ngọn quá mức làm chết cây.",
    silviculture: "Trồng dưới tán, 400–800 cây/ha. Giữ ẩm. Không phát sạch. Thu hái chừa ngọn.",
  },
  {
    slug: "gioi-gang",
    name: "Giổi găng",
    latin: "Paramichelia baillonii",
    family: "Magnoliaceae",
    image: "/images/sp/gioi-gang-tree.jpg",
    tags: ["quy", "trong"],
    status: "Gỗ bản địa — làm giàu",
    woodDensity: 0.5,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Tây Nguyên, Nam Trung Bộ, Đông Nam Bộ — rừng thường xanh ẩm.",
    uses: "Gỗ nhẹ thơm, ván, đóng đồ. Tầng tán.",
    rotation: "25–40 năm. Che bóng lúc nhỏ.",
    notes: "Hiện xếp Magnolia baillonii. Không nhầm giổi xanh (Michelia mediocris).",
    silviculture: "Trồng dưới tán thưa. Mật độ 1.100 cây/ha. Giữ ẩm năm đầu. Hỗn giao với mỡ, lát.",
  },
  {
    slug: "huyet-dang",
    name: "Huyết đằng",
    latin: "Sargentodoxa cuneata",
    family: "Lardizabalaceae",
    image: "/images/sp/huyet-dang-tree.jpg",
    tags: ["bao-ton", "nui"],
    status: "Dây leo thuốc",
    woodDensity: 0.45,
    formFactor: 0.5,
    allometric: "chave",
    habitat: "Đông Bắc, Hoàng Liên — rừng núi ẩm, bám cây chủ.",
    uses: "Thân dây làm thuốc (huyết đằng). Không lấy gỗ.",
    rotation: "Thu dây có kiểm soát, để lại gốc. Không khai thác trắng.",
    notes: "Dây leo, lá kép 3. Mặt cắt thân đỏ. Quần thể bị đào dây.",
    silviculture: "Bảo vệ cây chủ. Không phát dây hàng loạt. Trồng hỗ trợ dưới tán ẩm.",
  },
  {
    slug: "ma-tien-long",
    name: "Mã tiền lông",
    latin: "Strychnos ignatii",
    family: "Loganiaceae",
    image: "/images/sp/ma-tien-long-tree.jpg",
    tags: ["bao-ton"],
    status: "Dây leo — hạt độc",
    woodDensity: 0.55,
    formFactor: 0.5,
    allometric: "chave",
    habitat: "Rừng thường xanh Trung Bộ, Nam Bộ — dây leo dưới tán.",
    uses: "Hạt chứa strychnine — dược liệu kiểm soát. Không ăn. Không lấy gỗ.",
    rotation: "Không kinh doanh đại trà. Chỉ vườn dược liệu có phép.",
    notes: "Hạt rất độc. Lông trên dây/lá. Nhận biết để tránh. Không đốt, không cho trẻ em.",
    silviculture: "Giữ trong rừng. Vườn dược cách ly. Ghi chú độc khi điều tra rừng.",
  },
  {
    slug: "ma-tien-lang",
    name: "Mã tiền láng",
    latin: "Strychnos nitida",
    family: "Loganiaceae",
    image: "/images/sp/ma-tien-lang-tree.jpg",
    tags: ["bao-ton"],
    status: "Dây leo — hạt độc",
    woodDensity: 0.55,
    formFactor: 0.5,
    allometric: "chave",
    habitat: "Rừng thường xanh Bắc Trung Bộ, Trung Bộ — dây leo.",
    uses: "Hạt độc (strychnine). Dược liệu kiểm soát. Không ăn.",
    rotation: "Không kinh doanh đại trà.",
    notes: "Lá láng hơn mã tiền lông. Cùng độc tính. Dễ nhầm S. nux-vomica nhập.",
    silviculture: "Bảo tồn in-situ. Không khuyến khích thu hái hạt. Đánh dấu khi gặp trong điều tra rừng.",
  },
  {
    slug: "tau-muoi",
    name: "Táu muối",
    latin: "Vatica diospyroides",
    family: "Dipterocarpaceae",
    image: "/images/sp/tau-muoi-tree.jpg",
    tags: ["quy", "bao-ton"],
    status: "Gỗ quý — nhóm II",
    woodDensity: 0.78,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Nam Trung Bộ, Đông Nam Bộ — rừng mưa Dipterocarpaceae.",
    uses: "Gỗ táu đóng tàu, cầu. Không nhầm táu mật (Vatica subglabra).",
    rotation: "50–70 năm. Tái sinh cần che bóng.",
    notes: "Quả có cánh. Nguy cấp do mất rừng và chặt chọn. Không chịu cháy.",
    silviculture: "Nuôi dưỡng tái sinh dưới tán. Giữ cây mẹ. Không chặt trắng. Giữ ẩm năm đầu.",
  },
  {
    slug: "gioi-xanh",
    name: "Giổi xanh",
    latin: "Michelia mediocris",
    family: "Magnoliaceae",
    image: "/images/sp/gioi-xanh-tree.jpg",
    tags: ["quy", "trong"],
    status: "Gỗ bản địa — làm giàu rừng",
    woodDensity: 0.5,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Đông Bắc, Bắc Trung Bộ, Tây Nguyên — rừng thường xanh ẩm 300–1.000 m.",
    uses: "Gỗ nhẹ thơm, đóng đồ, ván. Hoa dùng làm cảnh và tinh dầu.",
    rotation: "25–40 năm. Che bóng lúc nhỏ, ưa sáng lúc lớn.",
    notes: "Hiện xếp Magnolia mediocris. Lá xanh bóng, hoa trắng. Không chịu cháy và đất úng.",
    silviculture: "Trồng dưới tán thưa hoặc hỗn giao với mỡ, lát. Mật độ 1.100 cây/ha. Giữ ẩm năm đầu.",
  },
  {
    slug: "voi-thuoc",
    name: "Vối thuốc",
    latin: "Schima wallichii",
    family: "Theaceae",
    image: "/images/sp/voi-thuoc-tree.jpg",
    tags: ["trong", "nui"],
    status: "Cây bản địa đa dụng",
    woodDensity: 0.6,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Tây Bắc, Việt Bắc, Tây Nguyên — 400–1.500 m, đất chua.",
    uses: "Gỗ xây dựng, củi. Vỏ và lá dùng trong y học cổ truyền. Phòng hộ đầu nguồn.",
    rotation: "25–35 năm. Tái sinh hạt mạnh sau cháy nhẹ.",
    notes: "Hoa trắng, chịu đất xấu. Thường gặp ven rừng thứ sinh. Không phải vối Eugenia.",
    silviculture: "Mật độ 1.100–1.600 cây/ha. Hỗn giao với sa mộc, thông. Chịu tỉa thưa.",
  },
  {
    slug: "boi-loi-do",
    name: "Bời lời đỏ",
    latin: "Litsea glutinosa",
    family: "Lauraceae",
    image: "/images/sp/boi-loi-do-tree.jpg",
    tags: ["trong"],
    status: "Cây đa dụng — vỏ nhầy",
    woodDensity: 0.45,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Cả nước ở rừng thứ sinh, đất trống, 0–800 m.",
    uses: "Vỏ nhầy làm nhang, keo dân gian. Gỗ củi. Lá và hạt dùng thuốc nam.",
    rotation: "Khai thác vỏ luân phiên 8–12 năm; không bóc vòng toàn thân.",
    notes: "Lá nhớt khi vò. Tái sinh chồi rất mạnh. Dễ nhầm với các Litsea khác.",
    silviculture: "Trồng phân tán, hàng rào, hoặc thuần loài mật độ 1.600 cây/ha. Để chồi sau chặt.",
  },
  {
    slug: "trom",
    name: "Trôm",
    latin: "Sterculia foetida",
    family: "Malvaceae",
    image: "/images/sp/trom-tree.jpg",
    tags: ["trong"],
    status: "Cây bóng mát — hạt và nhựa",
    woodDensity: 0.35,
    formFactor: 0.45,
    allometric: "chave",
    habitat: "Nam Trung Bộ, Đông Nam Bộ, Tây Nguyên — đất cát, chịu hạn, ven biển.",
    uses: "Hạt ăn được, nhựa trôm (sterculia gum). Gỗ nhẹ, phù. Cây bóng đô thị.",
    rotation: "Thu hạt từ năm thứ 8–10. Gỗ không phải mục tiêu chính.",
    notes: "Lá kép chân vịt, hoa hôi. Thân mập chứa nước. Chịu hạn rất tốt.",
    silviculture: "Cự ly 5×5 m hoặc trồng phân tán. Không cần bón nhiều. Tránh đất úng.",
  },
  {
    slug: "que",
    name: "Quế",
    latin: "Cinnamomum cassia",
    family: "Lauraceae",
    image: "/images/sp/que-tree.jpg",
    tags: ["trong"],
    status: "Cây đặc sản — vỏ quế",
    woodDensity: 0.5,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Yên Bái, Thanh Hóa, Quảng Nam, Quảng Ninh — 200–800 m, đất feralit ẩm.",
    uses: "Vỏ quế, tinh dầu (cinnamaldehyde). Gỗ phụ.",
    rotation: "Bóc vỏ 8–12 năm tùy thị trường. Để chồi, chu kỳ tiếp 6–8 năm.",
    notes: "Yên Bái là thủ phủ quế. Bóc đúng mùa, để lại đai vỏ liền da. Không nhầm với C. verum.",
    silviculture: "Mật độ 2.500–4.000 cây/ha lúc nhỏ, tỉa dần. Che bóng năm đầu. Không trồng đất úng.",
  },
  {
    slug: "hoi",
    name: "Hồi",
    latin: "Illicium verum",
    family: "Schisandraceae",
    image: "/images/sp/hoi-tree.jpg",
    tags: ["trong", "nui"],
    status: "Cây đặc sản — quả hồi",
    woodDensity: 0.5,
    formFactor: 0.48,
    allometric: "chave",
    habitat: "Lạng Sơn, Cao Bằng, Quảng Ninh — 300–900 m, khí hậu ẩm, sương mù.",
    uses: "Quả hồi (star anise), tinh dầu anethol. Gỗ không kinh doanh.",
    rotation: "Cho quả từ năm thứ 6–8, kinh doanh ổn định sau năm 12. Thọ vài chục năm.",
    notes: "Lạng Sơn chiếm phần lớn sản lượng thế giới. Sâu bệnh quả cần theo dõi. Không chặt cây lấy gỗ.",
    silviculture: "Mật độ 400–800 cây/ha. Ưa ẩm, che gió. Bón hữu cơ. Thu quả khi chín nâu, phơi ngay.",
  },
  {
    slug: "mac-ca",
    name: "Mắc ca",
    latin: "Macadamia integrifolia",
    family: "Proteaceae",
    image: "/images/sp/mac-ca-tree.jpg",
    tags: ["trong"],
    status: "Cây công nghiệp — hạt",
    woodDensity: 0.7,
    formFactor: 0.5,
    allometric: "chave",
    habitat: "Lâm Đồng, Đắk Lắk, Gia Lai — 600–1.200 m, mùa khô rõ, không sương muối nặng.",
    uses: "Hạt mắc ca. Tán phòng hộ vườn. Gỗ không phải mục tiêu.",
    rotation: "Cho quả năm thứ 5–7, ổn định sau năm 10. Vườn kinh doanh > 30 năm.",
    notes: "Cần thụ phấn chéo — trồng ít nhất hai giống. Tỉa tạo tán. Chuột và rệp là sâu hại chính.",
    silviculture: "Cự ly 8×8 hoặc 8×6 m. Tưới năm đầu. Không trồng đất úng. Tủ gốc giữ ẩm.",
  },
  {
    slug: "son-tra",
    name: "Sơn tra",
    latin: "Docynia indica",
    family: "Rosaceae",
    image: "/images/sp/son-tra-tree.jpg",
    tags: ["trong", "nui"],
    status: "Cây ăn quả núi cao",
    woodDensity: 0.65,
    formFactor: 0.48,
    allometric: "chave",
    habitat: "Tây Bắc, Hoàng Liên — 800–1.800 m, khí hậu á nhiệt đới.",
    uses: "Quả sơn tra (táo mèo) chế biến, rượu, dược. Gỗ cứng, phụ.",
    rotation: "Cho quả năm thứ 5–8. Vườn lưu hơn 25 năm.",
    notes: "Hoa trắng, quả vàng chua. Chịu lạnh. Không nhầm với sơn tra Docynia khác ở Vân Nam.",
    silviculture: "Cự ly 5×5 m. Tỉa tạo tán. Trồng thuần hoặc xen chè, sa mộc. Chống xói trên dốc.",
  },
  {
    slug: "tram-trang",
    name: "Trám trắng",
    latin: "Canarium album",
    family: "Burseraceae",
    image: "/images/sp/tram-trang-tree.jpg",
    tags: ["trong", "quy"],
    status: "Cây bản địa — hạt và nhựa",
    woodDensity: 0.55,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Bắc Trung Bộ, Đông Bắc — rừng thường xanh, đất sâu ẩm.",
    uses: "Hạt trám, nhựa. Gỗ xẻ nhóm trung. Cây bóng và làm giàu rừng.",
    rotation: "Thu hạt từ năm thứ 8–12. Gỗ 30–40 năm.",
    notes: "Quả trắng-vàng khi chín. Nhựa thơm. Tái sinh hạt dưới tán.",
    silviculture: "Trồng phân tán hoặc hỗn giao 400–800 cây/ha. Bảo vệ cây mẹ. Không chặt trắng.",
  },
  {
    slug: "tram-den",
    name: "Trám đen",
    latin: "Canarium tramdenum",
    family: "Burseraceae",
    image: "/images/sp/tram-den-tree.jpg",
    tags: ["trong", "quy"],
    status: "Cây bản địa — hạt trám",
    woodDensity: 0.55,
    formFactor: 0.47,
    allometric: "chave",
    habitat: "Đông Bắc, Bắc Trung Bộ — rừng thường xanh núi thấp.",
    uses: "Hạt trám đen (đặc sản). Gỗ và nhựa phụ.",
    rotation: "Cho hạt năm thứ 10–15. Cây lưu lâu năm.",
    notes: "Quả sẫm hơn trám trắng. Ít phổ biến trong trồng rừng thuần loài — ưu tiên vườn hộ và làm giàu.",
    silviculture: "Trồng phân tán, 200–400 cây/ha trong rừng nghèo. Che bóng năm đầu. Giữ ẩm.",
  },
  {
    slug: "tram-la-dai",
    name: "Tràm lá dài",
    latin: "Melaleuca leucadendra",
    family: "Myrtaceae",
    image: "/images/sp/tram-la-dai-tree.jpg",
    tags: ["trong", "ngap-man"],
    status: "Trồng rừng đất ngập",
    woodDensity: 0.65,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "Đồng bằng sông Cửu Long, ven biển — đất phèn, ngập theo mùa.",
    uses: "Cừ, củi, tinh dầu. Phục hồi đất phèn, đai xanh.",
    rotation: "Cừ 8–12 năm. Tái sinh chồi sau chặt.",
    notes: "Vỏ giấy, lá dài hơn tràm cừ. Chịu ngập. Không nhầm với M. cajuputi (tràm cừ).",
    silviculture: "Lên liếp. Mật độ 4.000–10.000 cây/ha lúc ban đầu, tỉa lấy cừ. Giữ mực nước.",
  },
  {
    slug: "tram",
    name: "Tràm cừ",
    latin: "Melaleuca cajuputi",
    family: "Myrtaceae",
    image: "/images/sp/tram-tree.jpg",
    tags: ["ngap-man", "bao-ton", "trong"],
    status: "Đặc hữu đất than bùn",
    woodDensity: 0.7,
    formFactor: 0.46,
    allometric: "chave",
    habitat: "U Minh Thượng, U Minh Hạ, Đồng Tháp Mười — đất than bùn phèn.",
    uses: "Cừ, củi, tinh dầu tràm. Giữ carbon trong than bùn.",
    rotation: "Khai thác cừ 8–12 năm trên rừng sản xuất; rừng đặc dụng không chặt.",
    notes: "Rừng tràm than bùn U Minh là kiểu hiếm. Cháy than bùn mùa khô — giữ mực nước là then chốt.",
    silviculture: "Tái sinh chồi mạnh sau chặt. Giữ mực nước ngầm; đào kênh quá mức sẽ oxy hóa phèn.",
  },
  {
    slug: "duoc-doi",
    name: "Đước đôi",
    latin: "Rhizophora apiculata",
    family: "Rhizophoraceae",
    image: "/images/sp/duoc-doi-tree.jpg",
    tags: ["ngap-man", "bao-ton"],
    status: "Phòng hộ ven biển",
    woodDensity: 0.9,
    formFactor: 0.5,
    allometric: "komiyama",
    habitat: "Cà Mau, Cần Giờ, cửa sông ĐBSCL và ven biển Trung Bộ.",
    uses: "Phòng hộ sóng, tích tụ phù sa, bãi đẻ thủy sản.",
    rotation: "Không khai thác thương mại trên rừng phòng hộ.",
    notes: "Rễ chống đặc trưng. Chịu ngập triều, độ mặn cao.",
    silviculture: "Trồng trên bãi bồi ổn định, 10.000–20.000 cây/ha lúc đầu. Bảo vệ 3–5 năm khỏi tàu thuyền.",
  },
  {
    slug: "ban-chua",
    name: "Bần chua",
    latin: "Sonneratia caseolaris",
    family: "Lythraceae",
    image: "/images/sp/ban-chua-tree.jpg",
    tags: ["ngap-man", "bao-ton"],
    status: "Phòng hộ cửa sông",
    woodDensity: 0.55,
    formFactor: 0.5,
    allometric: "komiyama",
    habitat: "Cửa sông ĐBSCL, Cần Giờ, Xuân Thủy — đai nước lợ, ít mặn hơn đước.",
    uses: "Phòng hộ, bãi giống thủy sản. Quả chua ăn được. Rễ thở đặc trưng.",
    rotation: "Không khai thác rừng phòng hộ. Phục hồi trên bãi bồi nước lợ.",
    notes: "Hoa đỏ, quả hình cầu. Pneumatophore (rễ thở) dày trên bùn. Tiền phong hơn đước ở cửa sông.",
    silviculture: "Trồng trên bãi bồi nước lợ, mật độ 2.500–5.000 cây/ha. Không trồng đai mặn cao — để đước.",
  },
  {
    slug: "tech",
    name: "Tếch",
    latin: "Tectona grandis",
    family: "Lamiaceae",
    image: "/images/sp/tech-tree.jpg",
    tags: ["trong", "quy"],
    status: "Trồng rừng",
    woodDensity: 0.65,
    formFactor: 0.45,
    allometric: "chave",
    habitat: "Đông Nam Bộ, Tây Nguyên — đất tốt, mùa khô rõ.",
    uses: "Gỗ đóng tàu, nội thất, sàn. Chịu mối mọt, ổn định kích thước.",
    rotation: "20–40 năm lấy gỗ xẻ; tỉa thưa lần đầu khoảng năm thứ 8–10.",
    notes: "Không phải loài bản địa nhưng đã trồng từ thời Pháp. Ngập úng kéo dài làm thối rễ.",
    silviculture: "Mật độ ban đầu 1.100–1.600 cây/ha. Giữ 250–400 cây/ha khi thành thục. Tỉa cành sớm.",
  },
  {
    slug: "giang-huong",
    name: "Giáng hương",
    latin: "Pterocarpus macrocarpus",
    family: "Fabaceae",
    image: "/images/sp/giang-huong-tree.jpg",
    tags: ["quy", "bao-ton"],
    status: "Sắp nguy cấp",
    woodDensity: 0.75,
    formFactor: 0.45,
    allometric: "chave",
    habitat: "Rừng khộp và nửa rụng lá Tây Nguyên, Đông Nam Bộ.",
    uses: "Gỗ đỏ đóng đồ cao cấp, nhạc cụ, điêu khắc.",
    rotation: "Không khai thác rừng tự nhiên. Trồng phân tán > 40 năm.",
    notes: "Gỗ sắc đỏ, giá trị cao nên bị khai thác trái phép. Tái sinh chậm.",
    silviculture: "Trồng hỗn giao với dầu, căm xe trên đất khộp. Che nhẹ lúc nhỏ, ưa sáng lúc lớn.",
  },
  {
    slug: "po-mu",
    name: "Pơ mu",
    latin: "Fokienia hodginsii",
    family: "Cupressaceae",
    image: "/images/sp/po-mu-tree.jpg",
    tags: ["nui", "bao-ton", "quy"],
    status: "Nguy cấp — bảo vệ nghiêm ngặt",
    woodDensity: 0.45,
    formFactor: 0.5,
    allometric: "chave",
    habitat: "Hoàng Liên Sơn, Lâm Đồng — rừng mây 1.200–1.800 m.",
    uses: "Gỗ thơm, đóng đồ thờ, hòm. Cấm tuyệt đối khai thác tự nhiên.",
    rotation: "Không kinh doanh. Chỉ bảo tồn và nghiên cứu.",
    notes: "Hạt trần quý của dãy Hoàng Liên. Gỗ có tinh dầu, bị săn lùng.",
    silviculture: "Bảo vệ in-situ. Vườn ươm từ hạt cây mẹ đã định danh. Không vận chuyển gỗ pơ mu.",
  },
];

export const FOREST_TYPES: ForestType[] = [
  {
    slug: "thuong-xanh",
    name: "Rừng kín thường xanh mưa ẩm nhiệt đới",
    image: "/images/forest-evergreen.jpg",
    region: "Dưới 700 m phía Bắc, dưới 1.000 m phía Nam — Trường Sơn, Tây Nguyên, Đông Bắc.",
    summary:
      "Kiểu rừng giàu loài nhất Việt Nam. Tầng vượt tán 35–50 m, dây leo và phụ sinh dày. Dipterocarpaceae, Lauraceae, Fagaceae chiếm ưu thế.",
    structure:
      "Bốn tầng rõ: vượt tán (dầu, sao, chò), tán chính, dưới tán, thảm tươi. Độ tàn che 0,8–1,0. Trữ lượng trạng thái IIIA–IIIB thường 150–250 m³/ha.",
    species: ["dau-rai", "sao-den", "lim-xanh", "lat-hoa", "gioi-xanh", "huynh", "sen", "tau-mat", "gu-lau", "tram-huong", "vu-huong"],
    management:
      "Khai thác chọn, giữ cây mẹ, nuôi dưỡng tái sinh. Cấm chặt trắng. Ưu tiên chứng chỉ quản lý rừng bền vững trên rừng sản xuất.",
  },
  {
    slug: "khop",
    name: "Rừng khộp — thưa lá rộng rụng lá",
    image: "/images/forest-khop.jpg",
    region: "Tây Nguyên (Yok Đôn, Ea Súp, Gia Lai), Đông Nam Bộ trên đất bazan và cát.",
    summary:
      "Quần thụ thưa, tầng tán 15–25 m, cháy nền theo mùa khô. Dipterocarpus tuberculatus, Shorea siamensis, căm xe, giáng hương.",
    structure:
      "Tàn che 0,3–0,6. Thảm cỏ tranh, lá rụng dày. Trữ lượng thấp 40–80 m³/ha nhưng giá trị bảo tồn thú lớn (voi, bò rừng) rất cao.",
    species: ["giang-huong", "dau-rai"],
    management:
      "Giữ chế độ cháy sớm có kiểm soát, không trồng keo thay thế. Yok Đôn là đối chứng quản lý kiểu rừng này.",
  },
  {
    slug: "thong",
    name: "Rừng thông á nhiệt đới núi thấp",
    image: "/images/forest-pine.jpg",
    region: "Lâm Đồng, Đà Lạt, Kon Tum, một phần Tây Bắc — 1.000–1.600 m.",
    summary:
      "Pinus kesiya (ba lá) và Pinus merkusii (nhựa) tạo quần thụ thuần loài hoặc hỗn giao với dẻ, re. Sương mù, mưa mùa hè.",
    structure:
      "Tầng tán đơn giản, dưới tán thưa. Dễ tích tụ vật liệu cháy. Trữ lượng 120–200 m³/ha khi được nuôi dưỡng.",
    species: ["thong-ba-la", "thong-nhua", "thong-ma-vi", "sa-moc"],
    management:
      "Tỉa thưa + băng cản lửa. Cạo nhựa đúng kỹ thuật. Pơ mu trong cùng đai cao phải được khoanh vùng bảo vệ riêng.",
  },
  {
    slug: "ngap-man",
    name: "Rừng ngập mặn",
    image: "/images/forest-mangrove.jpg",
    region: "Cà Mau, Cần Giờ, Xuân Thủy, Tam Giang — bãi bồi cửa sông.",
    summary:
      "Đước, vẹt, sú, mắm phân bố theo đai triều. Rễ chống và rễ thở. Lá chắn sóng, bãi giống thủy sản, carbon xanh.",
    structure:
      "Quần thụ thấp 8–20 m, mật độ cao. Sinh khối dưới đất (bùn, rễ) lớn hơn trên mặt đất. Không dùng công thức hình trụ thuần túy khi ước carbon.",
    species: ["duoc-doi", "ban-chua"],
    management:
      "Khoanh nuôi tái sinh tự nhiên trên bãi bồi, hạn chế đầm tôm trong đai rừng. Phục hồi bằng đước trên nền ổn định.",
  },
  {
    slug: "tram-u-minh",
    name: "Rừng tràm trên than bùn",
    image: "/images/forest-melaleuca.jpg",
    region: "U Minh Thượng, U Minh Hạ — Cà Mau / Kiên Giang (An Giang sau sáp nhập).",
    summary:
      "Kiểu rừng than bùn hiếm, sinh khối cao. Tràm chiếm ưu thế trên nền phèn. Giữ nước là giữ rừng.",
    structure:
      "Tầng tán 10–20 m, mật độ dày. Tầng than bùn chứa carbon tích tụ hàng thế kỷ — cháy ngầm phá hủy không phục hồi được trong đời người.",
    species: ["tram", "tram-la-dai"],
    management:
      "Điều tiết mực nước quanh năm. Cấm đào kênh làm khô. Tuần tra cháy 24/7 mùa khô.",
  },
  {
    slug: "rung-trong",
    name: "Rừng trồng sản xuất",
    image: "/images/sp/keo-lai-tree.jpg",
    region: "Cả nước — 4,89 triệu ha năm 2025, chiếm phần lớn tăng trưởng diện tích.",
    summary:
      "Keo lai, bạch đàn, một phần tèch và thông. Chu kỳ ngắn, cung cấp ~22 triệu m³ gỗ khai thác/năm theo kế hoạch ngành.",
    structure:
      "Quần thụ đồng tuổi, hàng lối. Trữ lượng lúc chặt 80–180 m³/ha tùy lập địa và chu kỳ. Đa dạng sinh học thấp.",
    species: ["keo-lai", "keo-tai-tuong", "keo-la-tram", "bach-dan-uro", "bach-dan-camal"],
    management:
      "Chuyển một phần sang gỗ lớn, chứng chỉ FSC/PEFC, luân loài và giữ hành lang ven suối. Không thay thế rừng tự nhiên.",
  },
];

export const FOREST_STATS = {
  year: 2025,
  coverPct: 42.03,
  totalHa: 14_971_553,
  naturalHa: 10_079_366,
  plantedHa: 4_892_187,
  source: "Quyết định 1106/QĐ-BNNMT — hiện trạng rừng 2025",
};

export function getSpecies(slug: string) {
  return SPECIES.find((s) => s.slug === slug);
}

export function foldVi(s: string) {
  return s
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/đ/gi, "d")
    .toLowerCase();
}

export function speciesMatches(s: Species, query: string) {
  const q = foldVi(query.trim());
  if (!q) return true;
  return (
    foldVi(s.name).includes(q) ||
    foldVi(s.latin).includes(q) ||
    foldVi(s.family).includes(q) ||
    s.slug.includes(q)
  );
}

export function getForest(slug: string) {
  return FOREST_TYPES.find((f) => f.slug === slug);
}
