/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CongCuRouteImport } from './routes/cong-cu'
import { Route as DuAnRouteImport } from './routes/du-an'
import { Route as KienThucRouteImport } from './routes/kien-thuc'
import { Route as LoaiRouteImport } from './routes/loai'
import { Route as OMauRouteImport } from './routes/o-mau'
import { Route as PhienBanRouteImport } from './routes/phien-ban'
import { Route as TaiApkRouteImport } from './routes/tai-apk'
import { Route as ThuVienRouteImport } from './routes/thu-vien'
import { Route as TracklogRouteImport } from './routes/tracklog'
import { Route as TyLeSongRouteImport } from './routes/ty-le-song'
import { Route as XuatCsvRouteImport } from './routes/xuat-csv'
import { Route as DuAnIndexRouteImport } from './routes/du-an.index'
import { Route as DuAnIdRouteImport } from './routes/du-an.$id'
import { Route as KienThucIndexRouteImport } from './routes/kien-thuc.index'
import { Route as KienThucSlugRouteImport } from './routes/kien-thuc.$slug'
import { Route as LoaiIndexRouteImport } from './routes/loai.index'
import { Route as LoaiSlugRouteImport } from './routes/loai.$slug'
import { Route as OMauIndexRouteImport } from './routes/o-mau.index'
import { Route as OMauIdRouteImport } from './routes/o-mau.$id'
import { Route as OMauOTieuChuanRouteImport } from './routes/o-mau.o-tieu-chuan'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CongCuRoute = CongCuRouteImport.update({
  id: '/cong-cu',
  path: '/cong-cu',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnRoute = DuAnRouteImport.update({
  id: '/du-an',
  path: '/du-an',
  getParentRoute: () => rootRouteImport,
} as any)
const KienThucRoute = KienThucRouteImport.update({
  id: '/kien-thuc',
  path: '/kien-thuc',
  getParentRoute: () => rootRouteImport,
} as any)
const LoaiRoute = LoaiRouteImport.update({
  id: '/loai',
  path: '/loai',
  getParentRoute: () => rootRouteImport,
} as any)
const OMauRoute = OMauRouteImport.update({
  id: '/o-mau',
  path: '/o-mau',
  getParentRoute: () => rootRouteImport,
} as any)
const PhienBanRoute = PhienBanRouteImport.update({
  id: '/phien-ban',
  path: '/phien-ban',
  getParentRoute: () => rootRouteImport,
} as any)
const TaiApkRoute = TaiApkRouteImport.update({
  id: '/tai-apk',
  path: '/tai-apk',
  getParentRoute: () => rootRouteImport,
} as any)
const ThuVienRoute = ThuVienRouteImport.update({
  id: '/thu-vien',
  path: '/thu-vien',
  getParentRoute: () => rootRouteImport,
} as any)
const TracklogRoute = TracklogRouteImport.update({
  id: '/tracklog',
  path: '/tracklog',
  getParentRoute: () => rootRouteImport,
} as any)
const TyLeSongRoute = TyLeSongRouteImport.update({
  id: '/ty-le-song',
  path: '/ty-le-song',
  getParentRoute: () => rootRouteImport,
} as any)
const XuatCsvRoute = XuatCsvRouteImport.update({
  id: '/xuat-csv',
  path: '/xuat-csv',
  getParentRoute: () => rootRouteImport,
} as any)
const DuAnIndexRoute = DuAnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DuAnRoute,
} as any)
const DuAnIdRoute = DuAnIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DuAnRoute,
} as any)
const KienThucIndexRoute = KienThucIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KienThucRoute,
} as any)
const KienThucSlugRoute = KienThucSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KienThucRoute,
} as any)
const LoaiIndexRoute = LoaiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoaiRoute,
} as any)
const LoaiSlugRoute = LoaiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LoaiRoute,
} as any)
const OMauIndexRoute = OMauIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OMauRoute,
} as any)
const OMauIdRoute = OMauIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OMauRoute,
} as any)
const OMauOTieuChuanRoute = OMauOTieuChuanRouteImport.update({
  id: '/o-tieu-chuan',
  path: '/o-tieu-chuan',
  getParentRoute: () => OMauRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cong-cu': typeof CongCuRoute
  '/du-an': typeof DuAnRouteWithChildren
  '/kien-thuc': typeof KienThucRouteWithChildren
  '/loai': typeof LoaiRouteWithChildren
  '/o-mau': typeof OMauRouteWithChildren
  '/phien-ban': typeof PhienBanRoute
  '/tai-apk': typeof TaiApkRoute
  '/thu-vien': typeof ThuVienRoute
  '/tracklog': typeof TracklogRoute
  '/ty-le-song': typeof TyLeSongRoute
  '/xuat-csv': typeof XuatCsvRoute
  '/du-an/$id': typeof DuAnIdRoute
  '/kien-thuc/$slug': typeof KienThucSlugRoute
  '/loai/$slug': typeof LoaiSlugRoute
  '/o-mau/$id': typeof OMauIdRoute
  '/o-mau/o-tieu-chuan': typeof OMauOTieuChuanRoute
  '/du-an/': typeof DuAnIndexRoute
  '/kien-thuc/': typeof KienThucIndexRoute
  '/loai/': typeof LoaiIndexRoute
  '/o-mau/': typeof OMauIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cong-cu': typeof CongCuRoute
  '/phien-ban': typeof PhienBanRoute
  '/tai-apk': typeof TaiApkRoute
  '/thu-vien': typeof ThuVienRoute
  '/tracklog': typeof TracklogRoute
  '/ty-le-song': typeof TyLeSongRoute
  '/xuat-csv': typeof XuatCsvRoute
  '/du-an/$id': typeof DuAnIdRoute
  '/kien-thuc/$slug': typeof KienThucSlugRoute
  '/loai/$slug': typeof LoaiSlugRoute
  '/o-mau/$id': typeof OMauIdRoute
  '/o-mau/o-tieu-chuan': typeof OMauOTieuChuanRoute
  '/du-an': typeof DuAnIndexRoute
  '/kien-thuc': typeof KienThucIndexRoute
  '/loai': typeof LoaiIndexRoute
  '/o-mau': typeof OMauIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cong-cu': typeof CongCuRoute
  '/du-an': typeof DuAnRouteWithChildren
  '/kien-thuc': typeof KienThucRouteWithChildren
  '/loai': typeof LoaiRouteWithChildren
  '/o-mau': typeof OMauRouteWithChildren
  '/phien-ban': typeof PhienBanRoute
  '/tai-apk': typeof TaiApkRoute
  '/thu-vien': typeof ThuVienRoute
  '/tracklog': typeof TracklogRoute
  '/ty-le-song': typeof TyLeSongRoute
  '/xuat-csv': typeof XuatCsvRoute
  '/du-an/$id': typeof DuAnIdRoute
  '/kien-thuc/$slug': typeof KienThucSlugRoute
  '/loai/$slug': typeof LoaiSlugRoute
  '/o-mau/$id': typeof OMauIdRoute
  '/o-mau/o-tieu-chuan': typeof OMauOTieuChuanRoute
  '/du-an/': typeof DuAnIndexRoute
  '/kien-thuc/': typeof KienThucIndexRoute
  '/loai/': typeof LoaiIndexRoute
  '/o-mau/': typeof OMauIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cong-cu'
    | '/du-an'
    | '/kien-thuc'
    | '/loai'
    | '/o-mau'
    | '/phien-ban'
    | '/tai-apk'
    | '/thu-vien'
    | '/tracklog'
    | '/ty-le-song'
    | '/xuat-csv'
    | '/du-an/$id'
    | '/kien-thuc/$slug'
    | '/loai/$slug'
    | '/o-mau/$id'
    | '/o-mau/o-tieu-chuan'
    | '/du-an/'
    | '/kien-thuc/'
    | '/loai/'
    | '/o-mau/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cong-cu'
    | '/phien-ban'
    | '/tai-apk'
    | '/thu-vien'
    | '/tracklog'
    | '/ty-le-song'
    | '/xuat-csv'
    | '/du-an/$id'
    | '/kien-thuc/$slug'
    | '/loai/$slug'
    | '/o-mau/$id'
    | '/o-mau/o-tieu-chuan'
    | '/du-an'
    | '/kien-thuc'
    | '/loai'
    | '/o-mau'
  id:
    | '__root__'
    | '/'
    | '/cong-cu'
    | '/du-an'
    | '/kien-thuc'
    | '/loai'
    | '/o-mau'
    | '/phien-ban'
    | '/tai-apk'
    | '/thu-vien'
    | '/tracklog'
    | '/ty-le-song'
    | '/xuat-csv'
    | '/du-an/$id'
    | '/kien-thuc/$slug'
    | '/loai/$slug'
    | '/o-mau/$id'
    | '/o-mau/o-tieu-chuan'
    | '/du-an/'
    | '/kien-thuc/'
    | '/loai/'
    | '/o-mau/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CongCuRoute: typeof CongCuRoute
  DuAnRoute: typeof DuAnRouteWithChildren
  KienThucRoute: typeof KienThucRouteWithChildren
  LoaiRoute: typeof LoaiRouteWithChildren
  OMauRoute: typeof OMauRouteWithChildren
  PhienBanRoute: typeof PhienBanRoute
  TaiApkRoute: typeof TaiApkRoute
  ThuVienRoute: typeof ThuVienRoute
  TracklogRoute: typeof TracklogRoute
  TyLeSongRoute: typeof TyLeSongRoute
  XuatCsvRoute: typeof XuatCsvRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-cu': {
      id: '/cong-cu'
      path: '/cong-cu'
      fullPath: '/cong-cu'
      preLoaderRoute: typeof CongCuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an': {
      id: '/du-an'
      path: '/du-an'
      fullPath: '/du-an'
      preLoaderRoute: typeof DuAnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kien-thuc': {
      id: '/kien-thuc'
      path: '/kien-thuc'
      fullPath: '/kien-thuc'
      preLoaderRoute: typeof KienThucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loai': {
      id: '/loai'
      path: '/loai'
      fullPath: '/loai'
      preLoaderRoute: typeof LoaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/o-mau': {
      id: '/o-mau'
      path: '/o-mau'
      fullPath: '/o-mau'
      preLoaderRoute: typeof OMauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phien-ban': {
      id: '/phien-ban'
      path: '/phien-ban'
      fullPath: '/phien-ban'
      preLoaderRoute: typeof PhienBanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tai-apk': {
      id: '/tai-apk'
      path: '/tai-apk'
      fullPath: '/tai-apk'
      preLoaderRoute: typeof TaiApkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thu-vien': {
      id: '/thu-vien'
      path: '/thu-vien'
      fullPath: '/thu-vien'
      preLoaderRoute: typeof ThuVienRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracklog': {
      id: '/tracklog'
      path: '/tracklog'
      fullPath: '/tracklog'
      preLoaderRoute: typeof TracklogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ty-le-song': {
      id: '/ty-le-song'
      path: '/ty-le-song'
      fullPath: '/ty-le-song'
      preLoaderRoute: typeof TyLeSongRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/xuat-csv': {
      id: '/xuat-csv'
      path: '/xuat-csv'
      fullPath: '/xuat-csv'
      preLoaderRoute: typeof XuatCsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-an/': {
      id: '/du-an/'
      path: '/'
      fullPath: '/du-an/'
      preLoaderRoute: typeof DuAnIndexRouteImport
      parentRoute: typeof DuAnRoute
    }
    '/du-an/$id': {
      id: '/du-an/$id'
      path: '/$id'
      fullPath: '/du-an/$id'
      preLoaderRoute: typeof DuAnIdRouteImport
      parentRoute: typeof DuAnRoute
    }
    '/kien-thuc/': {
      id: '/kien-thuc/'
      path: '/'
      fullPath: '/kien-thuc/'
      preLoaderRoute: typeof KienThucIndexRouteImport
      parentRoute: typeof KienThucRoute
    }
    '/kien-thuc/$slug': {
      id: '/kien-thuc/$slug'
      path: '/$slug'
      fullPath: '/kien-thuc/$slug'
      preLoaderRoute: typeof KienThucSlugRouteImport
      parentRoute: typeof KienThucRoute
    }
    '/loai/': {
      id: '/loai/'
      path: '/'
      fullPath: '/loai/'
      preLoaderRoute: typeof LoaiIndexRouteImport
      parentRoute: typeof LoaiRoute
    }
    '/loai/$slug': {
      id: '/loai/$slug'
      path: '/$slug'
      fullPath: '/loai/$slug'
      preLoaderRoute: typeof LoaiSlugRouteImport
      parentRoute: typeof LoaiRoute
    }
    '/o-mau/': {
      id: '/o-mau/'
      path: '/'
      fullPath: '/o-mau/'
      preLoaderRoute: typeof OMauIndexRouteImport
      parentRoute: typeof OMauRoute
    }
    '/o-mau/$id': {
      id: '/o-mau/$id'
      path: '/$id'
      fullPath: '/o-mau/$id'
      preLoaderRoute: typeof OMauIdRouteImport
      parentRoute: typeof OMauRoute
    }
    '/o-mau/o-tieu-chuan': {
      id: '/o-mau/o-tieu-chuan'
      path: '/o-tieu-chuan'
      fullPath: '/o-mau/o-tieu-chuan'
      preLoaderRoute: typeof OMauOTieuChuanRouteImport
      parentRoute: typeof OMauRoute
    }
  }
}

interface DuAnRouteChildren {
  DuAnIdRoute: typeof DuAnIdRoute
  DuAnIndexRoute: typeof DuAnIndexRoute
}

const DuAnRouteChildren: DuAnRouteChildren = {
  DuAnIdRoute: DuAnIdRoute,
  DuAnIndexRoute: DuAnIndexRoute,
}

const DuAnRouteWithChildren = DuAnRoute._addFileChildren(DuAnRouteChildren)

interface KienThucRouteChildren {
  KienThucSlugRoute: typeof KienThucSlugRoute
  KienThucIndexRoute: typeof KienThucIndexRoute
}

const KienThucRouteChildren: KienThucRouteChildren = {
  KienThucSlugRoute: KienThucSlugRoute,
  KienThucIndexRoute: KienThucIndexRoute,
}

const KienThucRouteWithChildren = KienThucRoute._addFileChildren(
  KienThucRouteChildren,
)

interface LoaiRouteChildren {
  LoaiSlugRoute: typeof LoaiSlugRoute
  LoaiIndexRoute: typeof LoaiIndexRoute
}

const LoaiRouteChildren: LoaiRouteChildren = {
  LoaiSlugRoute: LoaiSlugRoute,
  LoaiIndexRoute: LoaiIndexRoute,
}

const LoaiRouteWithChildren = LoaiRoute._addFileChildren(LoaiRouteChildren)

interface OMauRouteChildren {
  OMauIdRoute: typeof OMauIdRoute
  OMauOTieuChuanRoute: typeof OMauOTieuChuanRoute
  OMauIndexRoute: typeof OMauIndexRoute
}

const OMauRouteChildren: OMauRouteChildren = {
  OMauIdRoute: OMauIdRoute,
  OMauOTieuChuanRoute: OMauOTieuChuanRoute,
  OMauIndexRoute: OMauIndexRoute,
}

const OMauRouteWithChildren = OMauRoute._addFileChildren(OMauRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CongCuRoute: CongCuRoute,
  DuAnRoute: DuAnRouteWithChildren,
  KienThucRoute: KienThucRouteWithChildren,
  LoaiRoute: LoaiRouteWithChildren,
  OMauRoute: OMauRouteWithChildren,
  PhienBanRoute: PhienBanRoute,
  TaiApkRoute: TaiApkRoute,
  ThuVienRoute: ThuVienRoute,
  TracklogRoute: TracklogRoute,
  TyLeSongRoute: TyLeSongRoute,
  XuatCsvRoute: XuatCsvRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
